apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dev-renft-eks
  region: ap-northeast-1
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: dev-renft-api-aws-sa
        namespace: renft-app
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::955409730607:policy/dev-secret-manager-policy"

