version: "3.8"
services:
  stg-frontend:
    build:
      context: ./frontend
      dockerfile: ./stg_Dockerfile
    image: renft/stg-frontend
    container_name: frontend
    tty: true
    environment:
      - NODE_ENV=staging
    ports:
      - 8080:80
  stg-api:
    build:
      context: ./api
      dockerfile: ./stg_Dockerfile
    image: renft/stg-api
    container_name: api
    tty: true
    environment:
      - NODE_ENV=staging
    ports:
      - 8888:8888
