services:
  test-swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: test-swagger-ui
    ports:
      - "50000:8080"
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      API_URL: ./swagger.yaml

  # API Mock Server
  test-swagger-api:
    image: stoplight/prism:4.10.3
    container_name: 'test-swagger-api'
    ports:
      - "50001:4010"
    command: mock -h 0.0.0.0 /swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger.yaml