apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: renft-eks
  region: ap-northeast-1
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: renft-api-aws-sa
        namespace: renft-app
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::629667697317:policy/secret-manager-policy"

