openapi: 3.0.3

info:
  title: Social Good Web3 system
  description: Social Good API
  version: 1.0.0

servers:
- url: http://localhost:50001
  description: API Mock

paths:

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
  schemas:
